### ISSUE TITLE
SQL Error [XX000]: ERROR: GnuTLS recv error (-110): The TLS connection was non-properly terminated.

### ISSUE THREAD

**Issue by lincos-sergey** [pramsey/pgsql-http#128]
Hi,

First of all, thank you for the great Postgresql extension!
I met the following error while querying one particular website with https, while http is working fine.

When executing 
`select * FROM http_get('https://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl');`
I get this error:
SQL Error [XX000]: ERROR: GnuTLS recv error (-110): The TLS connection was non-properly terminated.

When executing 
`select * FROM http_get('http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl');`
everything works fine.

The server supports both http and https versions as specified here: https://ec.europa.eu/taxation_customs/vies/technicalInformation.html

In fact, if I use command line `curl` with these URLs, on the same machine where the Postgresql is running, both https and http work fine.

At the same time, other https queries work fine, for example `select * FROM http_get('https://github.com');` is working well.

What could be wrong here?
Thanks in advance,
Sergey

**Comment by pramsey** [comment]
Well, it took quite a while to find the answer and a work-around, but I'm a little at-sea as to how to make this not a problem in general. Basically, the particular HTTP server you are hitting is sitting behind a poorly configured reverse proxy, and that proxy will not accept HTTP connections that are set to "Close" when complete. It only accepts "Keep-alive" connections. 

The default for pgsql-http is to use "Close" connections, otherwise you end up with a lot of PgSQL back-end lying around with open sockets on HTTP servers for no good reason. It's a bit of a hard call, since presumably there are some performance benefits to having a open connections, if you're running a lot of HTTP calls in sequence, but...? 

Anyways, long story short, you can make that europa server work by turning on keep-alives.
```
set http.keepalive=true;
```

**Comment by lincos-sergey** [comment]
Works like a charm. Thank you for taking your time to check the issue.
