### ISSUE TITLE
Any chance to see Windows build?

### ISSUE THREAD

**Issue by SergeyMirvoda** [pramsey/pgsql-http#2]
at least instructions how to build it.

Thank you.

**Comment by robe2** [comment]
@SergeyMirvoda If you are still around, I have some windows builds you might want to try.  I've only compiled for PostgreSQL 9.4 64-bit but just as easy for me to do for 32-bit and for earlier versions of PostgreSQL.

I can write up some instructions, but I work in mingw64 environment so wouldn't work if compiling under VC++

**Comment by Babourius** [comment]
Hi Robe2,
I currently work on a 32 bits windows server, with PostgreSQL 8.4
Would it be possible for you to complie a build for this configuration , and explain :e how to install ?

Thanks in advance, and Happy Xmas Holidays

Babourius

**Comment by robe2** [comment]
@pramsey  feel free to close this one out.  I'll start including the 32-bits (9.4-9.6, I might include 9.3 as well since that's the last EDB version to support windows xp)  probably later this week or early next week on this link

http://www.postgresonline.com/journal/archives/371-http-extension.html
